import { CreationAttributes, QueryInterface } from "sequelize";
import Interest from "../../models/interest";
import { v4 as uuidv4 } from "uuid";
import { journal } from "../../types/models/journal";
import InterestType = journal.Interest;

export = {
  up: async (queryInterface: QueryInterface): Promise<void> => {
    await queryInterface.sequelize.transaction(async (transaction) => {
      const InterestObject: CreationAttributes<InterestType>[] = [
        { id: uuidv4(), name: "2D Material" },
        { id: uuidv4(), name: "5G" },
        { id: uuidv4(), name: "Access Control" },
        { id: uuidv4(), name: "Acoustic Waves" },
        { id: uuidv4(), name: "Acoustics" },
        { id: uuidv4(), name: "Active Computing" },
        { id: uuidv4(), name: "Ad-Hoc Network" },
        { id: uuidv4(), name: "Admission Control" },
        { id: uuidv4(), name: "Advection" },
        { id: uuidv4(), name: "Aerospace" },
        { id: uuidv4(), name: "Agricultural Engineering" },
        { id: uuidv4(), name: "Air Quality" },
        { id: uuidv4(), name: "Aircraft" },
        { id: uuidv4(), name: "Algebra" },
        { id: uuidv4(), name: "Amplifiers" },
        { id: uuidv4(), name: "Analog Circuit" },
        { id: uuidv4(), name: "Analog Design" },
        { id: uuidv4(), name: "Analog Integrated Circuits" },
        { id: uuidv4(), name: "Analog System" },
        { id: uuidv4(), name: "Anaphora Resolution" },
        { id: uuidv4(), name: "ANFIS" },
        { id: uuidv4(), name: "Anomalous Behavior" },
        { id: uuidv4(), name: "Ant Colony Optimization Algorithm" },
        { id: uuidv4(), name: "Antenna" },
        { id: uuidv4(), name: "Antenna and Propagation" },
        { id: uuidv4(), name: "Antenna Array" },
        { id: uuidv4(), name: "Antenna Design" },
        { id: uuidv4(), name: "Antenna Theory" },
        { id: uuidv4(), name: "Appied Mathematics" },
        { id: uuidv4(), name: "Application" },
        { id: uuidv4(), name: "Applied Computing and Computer" },
        { id: uuidv4(), name: "Applied Mathematics" },
        { id: uuidv4(), name: "Applied Superconductivity" },
        { id: uuidv4(), name: "Approximation Theory" },
        { id: uuidv4(), name: "Apriori Algorithm" },
        { id: uuidv4(), name: "Aquaculture" },
        { id: uuidv4(), name: "Arduino Micro Controller" },
        { id: uuidv4(), name: "Arithmetic Architecture" },
        { id: uuidv4(), name: "Array Processing" },
        { id: uuidv4(), name: "Artificial Inteligence" },
        { id: uuidv4(), name: "Artificial Neural Network" },
        { id: uuidv4(), name: "Artificial Vision" },
        { id: uuidv4(), name: "Attitude Control" },
        { id: uuidv4(), name: "Attribute Classification" },
        { id: uuidv4(), name: "Audio Engineering" },
        { id: uuidv4(), name: "Audio Features" },
        { id: uuidv4(), name: "Audio Signal Processing" },
        { id: uuidv4(), name: "Authentication" },
        { id: uuidv4(), name: "Automated Assessment" },
        { id: uuidv4(), name: "Automatic Control" },
        { id: uuidv4(), name: "Automatic Process Control" },
        { id: uuidv4(), name: "Automatic Speaker Recognition" },
        { id: uuidv4(), name: "Automatics" },
        { id: uuidv4(), name: "Automation" },
        { id: uuidv4(), name: "Automation and Control" },
        { id: uuidv4(), name: "Automation Engineering" },
        { id: uuidv4(), name: "Automation System" },
        { id: uuidv4(), name: "Automotive" },
        { id: uuidv4(), name: "Automotive Engineering" },
        { id: uuidv4(), name: "Autonomous System" },
        { id: uuidv4(), name: "Autonomous Vehicle" },
        { id: uuidv4(), name: "Bacterial Foraging Algorithm" },
        { id: uuidv4(), name: "Balanced Datasets of Five Types" },
        { id: uuidv4(), name: "Bandlet Transmission" },
        { id: uuidv4(), name: "Bat Algorithm" },
        { id: uuidv4(), name: "Battery" },
        { id: uuidv4(), name: "Battery Health Monitoring" },
        { id: uuidv4(), name: "Beam" },
        { id: uuidv4(), name: "Bee Colony" },
        { id: uuidv4(), name: "Big Data" },
        { id: uuidv4(), name: "Big Data Analytics" },
        { id: uuidv4(), name: "Big Data and Soft Computing" },
        { id: uuidv4(), name: "Big Data Security" },
        { id: uuidv4(), name: "Bilateral Control" },
        { id: uuidv4(), name: "Bio Telemetry" },
        { id: uuidv4(), name: "Bioinformatics" },
        { id: uuidv4(), name: "Biological Signal Processing" },
        { id: uuidv4(), name: "BioMedical" },
        { id: uuidv4(), name: "Biomedical Engineering" },
        { id: uuidv4(), name: "Biomedical Image Processing" },
        { id: uuidv4(), name: "Biomedical Instrumentation" },
        { id: uuidv4(), name: "Biomedical Signal" },
        { id: uuidv4(), name: "Biomedical Technology" },
        { id: uuidv4(), name: "Biometric" },
        { id: uuidv4(), name: "Biometric Images" },
        { id: uuidv4(), name: "Biosensor" },
        { id: uuidv4(), name: "Biosignal" },
        { id: uuidv4(), name: "Biotechnology" },
        { id: uuidv4(), name: "Block Cipher" },
        { id: uuidv4(), name: "Blockchain" },
        { id: uuidv4(), name: "Bluetooth" },
        { id: uuidv4(), name: "Brain Imaging" },
        { id: uuidv4(), name: "Broadband Access Networks" },
        { id: uuidv4(), name: "Broadband Wireless" },
        { id: uuidv4(), name: "Broadcast Engineering" },
        { id: uuidv4(), name: "Business Analytics" },
        { id: uuidv4(), name: "Business Informatics" },
        { id: uuidv4(), name: "Business Intelligence" },
        { id: uuidv4(), name: "Business Process Engineering" },
        { id: uuidv4(), name: "Business Process Management" },
        { id: uuidv4(), name: "Carbon" },
        { id: uuidv4(), name: "Cellular Network" },
        { id: uuidv4(), name: "Channel" },
        { id: uuidv4(), name: "Channel Coding" },
        { id: uuidv4(), name: "Channel Estimation" },
        { id: uuidv4(), name: "Chipless Rfid" },
        { id: uuidv4(), name: "Cipher" },
        { id: uuidv4(), name: "Circuit" },
        { id: uuidv4(), name: "Circuit and Systems" },
        { id: uuidv4(), name: "Circuit Fabrication Technique" },
        { id: uuidv4(), name: "Circuit Testing" },
        { id: uuidv4(), name: "Circuit Theory" },
        { id: uuidv4(), name: "Civil Engineering" },
        { id: uuidv4(), name: "Classification" },
        { id: uuidv4(), name: "Climatic" },
        { id: uuidv4(), name: "Cloud" },
        { id: uuidv4(), name: "Cloud Computing" },
        { id: uuidv4(), name: "Cloud Intelligence" },
        { id: uuidv4(), name: "Cloud Security" },
        { id: uuidv4(), name: "Clustering" },
        { id: uuidv4(), name: "Coding" },
        { id: uuidv4(), name: "Cognitive Computing" },
        { id: uuidv4(), name: "Cognitive Radio" },
        { id: uuidv4(), name: "Cognitive Relay Networs" },
        { id: uuidv4(), name: "Collaborative Applications" },
        { id: uuidv4(), name: "Collaborative Mobile Sinks" },
        { id: uuidv4(), name: "Color Image" },
        { id: uuidv4(), name: "Combinatorial Optimization" },
        { id: uuidv4(), name: "Combintorics" },
        { id: uuidv4(), name: "Communication" },
        { id: uuidv4(), name: "Communication and Computer Engineering" },
        { id: uuidv4(), name: "Communication and Electromagnetic Waves" },
        { id: uuidv4(), name: "Communication and Information Engineering" },
        { id: uuidv4(), name: "Communication and Network Security" },
        { id: uuidv4(), name: "Communication and Radar Engineering" },
        { id: uuidv4(), name: "Communication and Signal Processing" },
        { id: uuidv4(), name: "Communication Electronics" },
        { id: uuidv4(), name: "Communication Engineering" },
        { id: uuidv4(), name: "Communication Networks" },
        { id: uuidv4(), name: "Communication Protocol" },
        { id: uuidv4(), name: "Communication Systems" },
        { id: uuidv4(), name: "Communication Technology" },
        { id: uuidv4(), name: "Communications and Information Technology" },
        { id: uuidv4(), name: "Communications and Networking" },
        { id: uuidv4(), name: "Communications Engineering" },
        { id: uuidv4(), name: "Communications Satellites" },
        { id: uuidv4(), name: "Comparator" },
        { id: uuidv4(), name: "Comparator Design" },
        { id: uuidv4(), name: "Complex Event Processing" },
        { id: uuidv4(), name: "Complex Network" },
        {
          id: uuidv4(),
          name: "Composition of Components and Artificial Intelligence",
        },
        { id: uuidv4(), name: "Compressed Sensing" },
        { id: uuidv4(), name: "Compression" },
        { id: uuidv4(), name: "Computational" },
        { id: uuidv4(), name: "Computational Engineering" },
        { id: uuidv4(), name: "Computational Intelligence" },
        { id: uuidv4(), name: "Computational Linguistics" },
        { id: uuidv4(), name: "Computational Mathematics" },
        { id: uuidv4(), name: "Computer" },
        { id: uuidv4(), name: "Computer Aided Design" },
        { id: uuidv4(), name: "Computer Algorithm" },
        { id: uuidv4(), name: "Computer and Communication" },
        { id: uuidv4(), name: "Computer and Control Engineering" },
        { id: uuidv4(), name: "Computer and Electronic Engineering" },
        { id: uuidv4(), name: "Computer and Informatics" },
        { id: uuidv4(), name: "Computer and Information Science" },
        { id: uuidv4(), name: "Computer and Information Security" },
        { id: uuidv4(), name: "Computer and Information System" },
        { id: uuidv4(), name: "Computer and Information Technology" },
        { id: uuidv4(), name: "Computer and Simulations" },
        { id: uuidv4(), name: "Computer and Telecommunications" },
        { id: uuidv4(), name: "Computer Application" },
        { id: uuidv4(), name: "Computer Architecture" },
        { id: uuidv4(), name: "Computer Engineering" },
        { id: uuidv4(), name: "Computer Engineering Projects Management" },
        { id: uuidv4(), name: "Computer for Education" },
        { id: uuidv4(), name: "Computer Graphics" },
        { id: uuidv4(), name: "Computer Network" },
        { id: uuidv4(), name: "Computer Network Security" },
        { id: uuidv4(), name: "Computer Numerical Control" },
        { id: uuidv4(), name: "Computer Pattern Recognition" },
        { id: uuidv4(), name: "Computer Reasoning" },
        { id: uuidv4(), name: "Computer Science" },
        { id: uuidv4(), name: "Computer Security" },
        { id: uuidv4(), name: "Computer Theory" },
        { id: uuidv4(), name: "Computer Vision" },
        { id: uuidv4(), name: "Construction Management" },
        { id: uuidv4(), name: "Content Management" },
        { id: uuidv4(), name: "Control" },
        { id: uuidv4(), name: "Control and Instrumentation" },
        { id: uuidv4(), name: "Control and Optimization" },
        { id: uuidv4(), name: "Control Science and Engineering" },
        { id: uuidv4(), name: "Control System" },
        { id: uuidv4(), name: "Control System Engineering" },
        { id: uuidv4(), name: "Control Theory and Control Engineering" },
        { id: uuidv4(), name: "Converters" },
        { id: uuidv4(), name: "Convolutional Neural Network" },
        { id: uuidv4(), name: "Cooperative Communication" },
        { id: uuidv4(), name: "Copyright" },
        { id: uuidv4(), name: "Coumputer and Informatics" },
        { id: uuidv4(), name: "COVID-19" },
        { id: uuidv4(), name: "Cryptanalysis" },
        { id: uuidv4(), name: "Cryptography" },
        { id: uuidv4(), name: "Current Energy" },
        { id: uuidv4(), name: "Cyber Law" },
        { id: uuidv4(), name: "Cyber-physical System" },
        { id: uuidv4(), name: "Cybersecurity" },
        { id: uuidv4(), name: "Data Analysis" },
        { id: uuidv4(), name: "Data Augmentation" },
        { id: uuidv4(), name: "Data Center Risk Assessment" },
        { id: uuidv4(), name: "Data Clustering" },
        { id: uuidv4(), name: "Data Compression" },
        { id: uuidv4(), name: "Data Embedding" },
        { id: uuidv4(), name: "Data Engineering" },
        { id: uuidv4(), name: "Data Fusion" },
        { id: uuidv4(), name: "Data Gathering" },
        { id: uuidv4(), name: "Data Injection" },
        { id: uuidv4(), name: "Data Mining" },
        { id: uuidv4(), name: "Data Mining Algorithm" },
        { id: uuidv4(), name: "Data Mining Decision Making" },
        { id: uuidv4(), name: "Data Prediction" },
        { id: uuidv4(), name: "Data Protection" },
        { id: uuidv4(), name: "Data Retrieval" },
        { id: uuidv4(), name: "Data Science" },
        { id: uuidv4(), name: "Data Security" },
        { id: uuidv4(), name: "Data Storage" },
        { id: uuidv4(), name: "Data Visualization" },
        { id: uuidv4(), name: "Data Warehousing" },
        { id: uuidv4(), name: "Database" },
        { id: uuidv4(), name: "Database Management System" },
        { id: uuidv4(), name: "Data-driven Controller" },
        { id: uuidv4(), name: "Dataset" },
        { id: uuidv4(), name: "Deadlock Detection" },
        { id: uuidv4(), name: "Decision Making" },
        { id: uuidv4(), name: "Decision Support System" },
        { id: uuidv4(), name: "Decision Tree" },
        { id: uuidv4(), name: "Decision-making Information System" },
        { id: uuidv4(), name: "Deep Learning" },
        { id: uuidv4(), name: "Delay Tolerant Networks" },
        { id: uuidv4(), name: "Demand-side Load Management" },
        { id: uuidv4(), name: "Demand-side Response" },
        { id: uuidv4(), name: "Desain and Computer Engineering" },
        { id: uuidv4(), name: "Design Power System" },
        { id: uuidv4(), name: "Detection Technology and Automatic Equipment" },
        { id: uuidv4(), name: "Device and Circuit" },
        { id: uuidv4(), name: "Device Architecture" },
        { id: uuidv4(), name: "Device Modeling" },
        { id: uuidv4(), name: "Device Physics" },
        { id: uuidv4(), name: "Digital Communication" },
        { id: uuidv4(), name: "Digital Communications" },
        { id: uuidv4(), name: "Digital Electronic" },
        { id: uuidv4(), name: "Digital Forensics" },
        { id: uuidv4(), name: "Digital Frequency Synthesis" },
        { id: uuidv4(), name: "Digital Image Processing" },
        { id: uuidv4(), name: "Digital Marketing" },
        { id: uuidv4(), name: "Digital Signal Processing" },
        { id: uuidv4(), name: "Digital System Design" },
        { id: uuidv4(), name: "Digital Video Watermarking" },
        { id: uuidv4(), name: "Dimensionalty Reduction" },
        { id: uuidv4(), name: "Direct Converter" },
        { id: uuidv4(), name: "Discrete Cosine Transform" },
        { id: uuidv4(), name: "Discrete Wavelet Transform" },
        { id: uuidv4(), name: "Disease Modelling" },
        { id: uuidv4(), name: "Distributed Generation" },
        { id: uuidv4(), name: "Distributed Software" },
        { id: uuidv4(), name: "Distributed System" },
        { id: uuidv4(), name: "Distribution Networks" },
        { id: uuidv4(), name: "Distribution Power System" },
        { id: uuidv4(), name: "Distribution System" },
        { id: uuidv4(), name: "Distribution Systems" },
        { id: uuidv4(), name: "Disturbance Observer" },
        { id: uuidv4(), name: "DNS Tunneling" },
        { id: uuidv4(), name: "Ecology" },
        { id: uuidv4(), name: "E-Commerce" },
        { id: uuidv4(), name: "E-Commputing" },
        { id: uuidv4(), name: "Edge Computing" },
        { id: uuidv4(), name: "Education" },
        { id: uuidv4(), name: "Education Technology" },
        { id: uuidv4(), name: "Educational Data Mining" },
        { id: uuidv4(), name: "E-Government" },
        { id: uuidv4(), name: "E-Health" },
        { id: uuidv4(), name: "E-Learning" },
        { id: uuidv4(), name: "Electric" },
        { id: uuidv4(), name: "Electric and Electronics Power" },
        { id: uuidv4(), name: "Electric and Vehicle" },
        { id: uuidv4(), name: "Electric Circuits" },
        { id: uuidv4(), name: "Electric Drives and Control" },
        { id: uuidv4(), name: "Electric Power Engineering" },
        { id: uuidv4(), name: "Electric Vehicle" },
        { id: uuidv4(), name: "Electrical" },
        { id: uuidv4(), name: "Electrical and Computer Engineering" },
        { id: uuidv4(), name: "Electrical and Electronic Engineering" },
        { id: uuidv4(), name: "Electrical and Electronics" },
        { id: uuidv4(), name: "Electrical Design" },
        { id: uuidv4(), name: "Electrical Drives and Control" },
        { id: uuidv4(), name: "Electrical Energy" },
        { id: uuidv4(), name: "Electrical Engineering" },
        { id: uuidv4(), name: "Electrical Engineering and Physics" },
        { id: uuidv4(), name: "Electrical Machine" },
        { id: uuidv4(), name: "Electrical Machine Control" },
        { id: uuidv4(), name: "Electrical Maintenance" },
        { id: uuidv4(), name: "Electrical Material" },
        { id: uuidv4(), name: "Electrical Networks" },
        { id: uuidv4(), name: "Electrical Optimization" },
        { id: uuidv4(), name: "Electrical Performance" },
        { id: uuidv4(), name: "Electrical Power" },
        { id: uuidv4(), name: "Electrical Power System and Automation" },
        { id: uuidv4(), name: "Electrical Power System and Renewable Energy" },
        { id: uuidv4(), name: "Electrical Power Systems Engineering" },
        { id: uuidv4(), name: "Electrical Power Transmission" },
        { id: uuidv4(), name: "Electrical System Automation" },
        { id: uuidv4(), name: "Electrocardiography" },
        { id: uuidv4(), name: "Electroencephalography" },
        { id: uuidv4(), name: "Electromagnetic" },
        { id: uuidv4(), name: "Electromechanical Engineering" },
        { id: uuidv4(), name: "Electromedical Engineering" },
        { id: uuidv4(), name: "Electronic" },
        { id: uuidv4(), name: "Electrotechnical Engineering" },
        { id: uuidv4(), name: "Embedded Real-time Systems" },
        { id: uuidv4(), name: "Embedded System" },
        { id: uuidv4(), name: "Emotion Analysis" },
        { id: uuidv4(), name: "Encoder" },
        { id: uuidv4(), name: "Encryption" },
        { id: uuidv4(), name: "Energy" },
        { id: uuidv4(), name: "Energy Consumption and Production" },
        { id: uuidv4(), name: "Energy Control" },
        { id: uuidv4(), name: "Energy Economy" },
        { id: uuidv4(), name: "Energy Efficiency" },
        { id: uuidv4(), name: "Energy Engineering" },
        { id: uuidv4(), name: "Energy Harvesting" },
        { id: uuidv4(), name: "Energy Management" },
        { id: uuidv4(), name: "Energy Saving" },
        { id: uuidv4(), name: "Energy Storage" },
        { id: uuidv4(), name: "Energy Systems" },
        { id: uuidv4(), name: "Engineering and Control" },
        { id: uuidv4(), name: "Ensemble Learning" },
        { id: uuidv4(), name: "Enterprise Architecture" },
        { id: uuidv4(), name: "Enterprise Governance" },
        { id: uuidv4(), name: "Enterprise Resource Planning" },
        { id: uuidv4(), name: "Environmental" },
        { id: uuidv4(), name: "E-Payment" },
        { id: uuidv4(), name: "Error Correction Codes" },
        { id: uuidv4(), name: "E-Security" },
        { id: uuidv4(), name: "Evolutionary Algorithms" },
        { id: uuidv4(), name: "Evolutionary Computation" },
        { id: uuidv4(), name: "Expert System" },
        { id: uuidv4(), name: "Eye Health" },
        { id: uuidv4(), name: "Face Detection" },
        { id: uuidv4(), name: "Face Recognition" },
        { id: uuidv4(), name: "Face Retrieval" },
        { id: uuidv4(), name: "FACTS" },
        { id: uuidv4(), name: "Fault Location" },
        { id: uuidv4(), name: "Fault Tolerance" },
        { id: uuidv4(), name: "Faults on Grid" },
        { id: uuidv4(), name: "Feature Engineering" },
        { id: uuidv4(), name: "Fingerprint" },
        { id: uuidv4(), name: "Fluid Power Control" },
        { id: uuidv4(), name: "Fog Computing" },
        { id: uuidv4(), name: "Food Processing" },
        { id: uuidv4(), name: "Forecasting" },
        { id: uuidv4(), name: "Forestry" },
        { id: uuidv4(), name: "Forgery" },
        { id: uuidv4(), name: "FPGA" },
        { id: uuidv4(), name: "Fractal Antenna" },
        { id: uuidv4(), name: "Free Space Optics" },
        { id: uuidv4(), name: "Frequency Inverters" },
        { id: uuidv4(), name: "Fundus Image Analysis" },
        { id: uuidv4(), name: "Fuzzy Logic" },
        { id: uuidv4(), name: "Game Development" },
        { id: uuidv4(), name: "General Artificial Intelligence" },
        { id: uuidv4(), name: "Generalized State Identifier" },
        { id: uuidv4(), name: "Generative Networks" },
        { id: uuidv4(), name: "Genetic Algorithm" },
        { id: uuidv4(), name: "Geolocation" },
        { id: uuidv4(), name: "Government Data" },
        { id: uuidv4(), name: "GPU Computing" },
        { id: uuidv4(), name: "Graph Mining" },
        { id: uuidv4(), name: "GSM" },
        { id: uuidv4(), name: "Hadoop" },
        { id: uuidv4(), name: "Haptic Sensation" },
        { id: uuidv4(), name: "Hardware" },
        { id: uuidv4(), name: "Hash" },
        { id: uuidv4(), name: "Health Information Management" },
        { id: uuidv4(), name: "Health Information Systems" },
        { id: uuidv4(), name: "Health Policy" },
        { id: uuidv4(), name: "Healthcare Monitoring" },
        { id: uuidv4(), name: "Healthcare Systems" },
        { id: uuidv4(), name: "Herbal Plant Recognition" },
        { id: uuidv4(), name: "Heterogeneous Computing" },
        { id: uuidv4(), name: "Heuristic Optimization" },
        { id: uuidv4(), name: "Heuristics Approach" },
        { id: uuidv4(), name: "High Speed Railway" },
        { id: uuidv4(), name: "High Voltage" },
        { id: uuidv4(), name: "High-dimensional Statistical Modeling" },
        { id: uuidv4(), name: "Homology Modeling" },
        { id: uuidv4(), name: "Hospital Logistic" },
        { id: uuidv4(), name: "HR Analytics" },
        { id: uuidv4(), name: "HTML" },
        { id: uuidv4(), name: "Human Computer Interaction" },
        { id: uuidv4(), name: "Human Intelligence" },
        { id: uuidv4(), name: "Hybrid and Switching Control" },
        { id: uuidv4(), name: "Hybrid Power System" },
        { id: uuidv4(), name: "Hybrid Renewable Energy" },
        { id: uuidv4(), name: "Hybrid System" },
        { id: uuidv4(), name: "Hybrid Vehicle" },
        { id: uuidv4(), name: "Hydropower Engineering" },
        { id: uuidv4(), name: "Hyperfrequency" },
        { id: uuidv4(), name: "Hyperparameter Selection" },
        { id: uuidv4(), name: "Image Analysis" },
        { id: uuidv4(), name: "Image Classification" },
        { id: uuidv4(), name: "Image Compression" },
        { id: uuidv4(), name: "Image Enhancement" },
        { id: uuidv4(), name: "Image Filtering" },
        { id: uuidv4(), name: "Image Processing" },
        { id: uuidv4(), name: "Image Quality Assessment" },
        { id: uuidv4(), name: "Image Recognition" },
        { id: uuidv4(), name: "Image Retrieval" },
        { id: uuidv4(), name: "Image Steganography" },
        { id: uuidv4(), name: "Imbedded Systems" },
        { id: uuidv4(), name: "Indoor Network" },
        { id: uuidv4(), name: "Induction Motor Control" },
        { id: uuidv4(), name: "Inductive Coupling" },
        { id: uuidv4(), name: "Industrial Automation" },
        { id: uuidv4(), name: "Industrial Electronics" },
        { id: uuidv4(), name: "Industrial Engineering" },
        { id: uuidv4(), name: "Industrial Internet of Things" },
        { id: uuidv4(), name: "Industrial Technology" },
        { id: uuidv4(), name: "Informatics Engineering" },
        { id: uuidv4(), name: "Information and Communication" },
        { id: uuidv4(), name: "Information Engineering" },
        { id: uuidv4(), name: "Information Extraction" },
        { id: uuidv4(), name: "Information Hiding" },
        { id: uuidv4(), name: "Information Management" },
        { id: uuidv4(), name: "Information Management System" },
        { id: uuidv4(), name: "Information Processing" },
        { id: uuidv4(), name: "Information Retrieval" },
        { id: uuidv4(), name: "Information Science" },
        { id: uuidv4(), name: "Information Security" },
        { id: uuidv4(), name: "Information System" },
        { id: uuidv4(), name: "Information System Project Management" },
        { id: uuidv4(), name: "Information Technology" },
        { id: uuidv4(), name: "Information Theory" },
        { id: uuidv4(), name: "Instructional Technology" },
        { id: uuidv4(), name: "Instrumentation" },
        { id: uuidv4(), name: "Intelligent Algorithm" },
        { id: uuidv4(), name: "Intelligent Control" },
        { id: uuidv4(), name: "Intelligent Data Analysis and Data Mining" },
        { id: uuidv4(), name: "Intelligent Decision Support" },
        { id: uuidv4(), name: "Intelligent Planning" },
        { id: uuidv4(), name: "Intelligent Robotics" },
        { id: uuidv4(), name: "Intelligent System" },
        { id: uuidv4(), name: "Intelligent Systems" },
        { id: uuidv4(), name: "Intelligent Transportation System" },
        { id: uuidv4(), name: "Interconnection Network" },
        { id: uuidv4(), name: "Interference" },
        { id: uuidv4(), name: "Internet Network" },
        { id: uuidv4(), name: "Internet of Things" },
        { id: uuidv4(), name: "Intrumentation and Control" },
        { id: uuidv4(), name: "Intrumentation and Signal Processing" },
        { id: uuidv4(), name: "Intrusion Detection System" },
        { id: uuidv4(), name: "Inverters" },
        { id: uuidv4(), name: "IP Over Satellites" },
        { id: uuidv4(), name: "Islanding Detection" },
        { id: uuidv4(), name: "IT Convergence" },
        { id: uuidv4(), name: "IT Engineer" },
        { id: uuidv4(), name: "IT Governance" },
        { id: uuidv4(), name: "K-means" },
        { id: uuidv4(), name: "Knowledge Discovery" },
        { id: uuidv4(), name: "Knowledge Engineering" },
        { id: uuidv4(), name: "Knowledge Management" },
        { id: uuidv4(), name: "Knowledge Modelling" },
        { id: uuidv4(), name: "Knowledge Representation" },
        { id: uuidv4(), name: "Law" },
        { id: uuidv4(), name: "Linked Data" },
        { id: uuidv4(), name: "Linux" },
        { id: uuidv4(), name: "Load Balancing" },
        { id: uuidv4(), name: "Load Forecasting" },
        { id: uuidv4(), name: "Load Scheduling" },
        { id: uuidv4(), name: "Logistic Regression" },
        { id: uuidv4(), name: "Logistic Traceability" },
        { id: uuidv4(), name: "Low Power" },
        { id: uuidv4(), name: "LTE" },
        { id: uuidv4(), name: "Machine" },
        { id: uuidv4(), name: "Machine Interface" },
        { id: uuidv4(), name: "Machine Learning" },
        { id: uuidv4(), name: "Machine Translation" },
        { id: uuidv4(), name: "Machine Vision" },
        { id: uuidv4(), name: "Maintenance" },
        { id: uuidv4(), name: "Malware Detection" },
        { id: uuidv4(), name: "Management Information System" },
        { id: uuidv4(), name: "Manufacturing Technology" },
        { id: uuidv4(), name: "Material Science" },
        { id: uuidv4(), name: "Mathematical Modeling" },
        { id: uuidv4(), name: "Mathematical Sciences" },
        { id: uuidv4(), name: "Mathematics" },
        { id: uuidv4(), name: "Mechanical and Electronics Engineering" },
        { id: uuidv4(), name: "Mechanical Engineering" },
        { id: uuidv4(), name: "Mechatronic" },
        { id: uuidv4(), name: "Medical" },
        { id: uuidv4(), name: "Medical Engineering" },
        { id: uuidv4(), name: "Medical Image Processing" },
        { id: uuidv4(), name: "Medical Image Segmentation" },
        { id: uuidv4(), name: "Medical Informatic" },
        { id: uuidv4(), name: "Medical Instrumentation" },
        { id: uuidv4(), name: "Medical Robotics" },
        { id: uuidv4(), name: "Medical Science" },
        { id: uuidv4(), name: "Medicine" },
        { id: uuidv4(), name: "Medicine and Health" },
        { id: uuidv4(), name: "Membrane Computing" },
        { id: uuidv4(), name: "Memristor" },
        { id: uuidv4(), name: "MetaData" },
        { id: uuidv4(), name: "Metaheuristic" },
        { id: uuidv4(), name: "Metaheuristic Algorithm" },
        { id: uuidv4(), name: "Metamaterial Loss" },
        { id: uuidv4(), name: "Meteorology" },
        { id: uuidv4(), name: "Metratronics" },
        { id: uuidv4(), name: "Metrics" },
        { id: uuidv4(), name: "Micro Fabrication" },
        { id: uuidv4(), name: "Micro Grid" },
        { id: uuidv4(), name: "Microcontroller" },
        { id: uuidv4(), name: "Microelectromechanical" },
        { id: uuidv4(), name: "Microelectronic" },
        { id: uuidv4(), name: "Microfluidic" },
        { id: uuidv4(), name: "Microstrip Patch Antenna" },
        { id: uuidv4(), name: "Microtechnology" },
        { id: uuidv4(), name: "Microwave" },
        { id: uuidv4(), name: "Microwave Circuits" },
        { id: uuidv4(), name: "Microwave Electronics" },
        { id: uuidv4(), name: "Microwave Engineering" },
        { id: uuidv4(), name: "Microwave Power" },
        { id: uuidv4(), name: "Millimeter Wave" },
        { id: uuidv4(), name: "MIMO System" },
        { id: uuidv4(), name: "Mine Safety" },
        { id: uuidv4(), name: "Miniaturized Antenna" },
        { id: uuidv4(), name: "Mobile Adhoc Network" },
        { id: uuidv4(), name: "Mobile Application" },
        { id: uuidv4(), name: "Mobile Communication" },
        { id: uuidv4(), name: "Mobile Computing" },
        { id: uuidv4(), name: "Mobile Forensics" },
        { id: uuidv4(), name: "Mobile Information Processing Systems" },
        { id: uuidv4(), name: "Mobile Learning" },
        { id: uuidv4(), name: "Mobile Malware" },
        { id: uuidv4(), name: "Mobile Networks" },
        { id: uuidv4(), name: "Mobile Sensor Networks" },
        { id: uuidv4(), name: "Mobile Systems" },
        { id: uuidv4(), name: "Mobile Technology" },
        { id: uuidv4(), name: "Mobility Management Protocols" },
        { id: uuidv4(), name: "Model Predictive Control" },
        { id: uuidv4(), name: "Modelling" },
        { id: uuidv4(), name: "Modelling and Simulation" },
        { id: uuidv4(), name: "Modelling of Electric Machines" },
        { id: uuidv4(), name: "Modern Control" },
        { id: uuidv4(), name: "Monitoring and Control" },
        { id: uuidv4(), name: "Motion Control" },
        { id: uuidv4(), name: "Motor Control" },
        { id: uuidv4(), name: "Motor Drive" },
        { id: uuidv4(), name: "Multi Agent System" },
        { id: uuidv4(), name: "Multi Criteria Decision Analysis" },
        { id: uuidv4(), name: "Multibands" },
        { id: uuidv4(), name: "Multimedia" },
        { id: uuidv4(), name: "Multimedia Communication" },
        { id: uuidv4(), name: "Multimedia Security" },
        { id: uuidv4(), name: "Multipath Scheduler" },
        { id: uuidv4(), name: "Multiple Kernel Learning" },
        { id: uuidv4(), name: "Multiple Mobile Elements" },
        { id: uuidv4(), name: "Multiplier" },
        { id: uuidv4(), name: "Multiport" },
        { id: uuidv4(), name: "Multiprocessor" },
        { id: uuidv4(), name: "Multispectral" },
        { id: uuidv4(), name: "Naive Bayes" },
        { id: uuidv4(), name: "Nano Transistor" },
        { id: uuidv4(), name: "Nanoelectronics" },
        { id: uuidv4(), name: "Nanomaterials" },
        { id: uuidv4(), name: "Nanoscale Technology" },
        { id: uuidv4(), name: "Nanotechnology" },
        { id: uuidv4(), name: "Natural and Applied Sciences" },
        { id: uuidv4(), name: "Natural Language Processing" },
        { id: uuidv4(), name: "Nature-inspired Method" },
        { id: uuidv4(), name: "Navigation" },
        { id: uuidv4(), name: "Network" },
        { id: uuidv4(), name: "Network and Information Security" },
        { id: uuidv4(), name: "Network Engineering" },
        { id: uuidv4(), name: "Network Monitoring" },
        { id: uuidv4(), name: "Network Reliability" },
        { id: uuidv4(), name: "Network Security" },
        { id: uuidv4(), name: "Network Traffic" },
        { id: uuidv4(), name: "Neural Network" },
        { id: uuidv4(), name: "Neuro Fuzzy" },
        { id: uuidv4(), name: "NonLinear and Stochastic Controls" },
        { id: uuidv4(), name: "Nonlinear Control" },
        { id: uuidv4(), name: "Nutritionand Dietetics" },
        { id: uuidv4(), name: "Object Recognition" },
        { id: uuidv4(), name: "Object Tracking" },
        { id: uuidv4(), name: "OCR" },
        { id: uuidv4(), name: "OFDM" },
        { id: uuidv4(), name: "Oil Extraction" },
        { id: uuidv4(), name: "On Chip Communication" },
        { id: uuidv4(), name: "Online Teaching" },
        { id: uuidv4(), name: "Ontologies" },
        { id: uuidv4(), name: "Open Data" },
        { id: uuidv4(), name: "Operating System" },
        { id: uuidv4(), name: "Operating Systems" },
        { id: uuidv4(), name: "Opinion Mining" },
        { id: uuidv4(), name: "Optical Communication" },
        { id: uuidv4(), name: "Optical Electronic" },
        { id: uuidv4(), name: "Optical Fiber" },
        { id: uuidv4(), name: "Optical Networks" },
        { id: uuidv4(), name: "Optical Properties" },
        { id: uuidv4(), name: "Optical Sensing" },
        { id: uuidv4(), name: "Optical Wireless Communication" },
        { id: uuidv4(), name: "Optics" },
        { id: uuidv4(), name: "Optimal" },
        { id: uuidv4(), name: "Optimization" },
        { id: uuidv4(), name: "Optimization Algorithm" },
        { id: uuidv4(), name: "Optimization Methods" },
        { id: uuidv4(), name: "Optimization Process" },
        { id: uuidv4(), name: "Optimization Technique" },
        { id: uuidv4(), name: "Outdoor Wireless Communications" },
        { id: uuidv4(), name: "Parallel Computing" },
        { id: uuidv4(), name: "Parallel Distributed Computation" },
        { id: uuidv4(), name: "Particle Swarm Optimization" },
        { id: uuidv4(), name: "PatchA ntenna" },
        { id: uuidv4(), name: "Pattern Recognition" },
        { id: uuidv4(), name: "Performance Evaluation" },
        { id: uuidv4(), name: "Performance Management" },
        { id: uuidv4(), name: "Pervasive Computing" },
        { id: uuidv4(), name: "Phase Angle" },
        { id: uuidv4(), name: "Photoelectronics" },
        { id: uuidv4(), name: "Photogammetric" },
        { id: uuidv4(), name: "Photography" },
        { id: uuidv4(), name: "Photovoltaic" },
        { id: uuidv4(), name: "Photovoltaic Panel" },
        { id: uuidv4(), name: "Physics" },
        { id: uuidv4(), name: "PID Control" },
        { id: uuidv4(), name: "Plant Disease" },
        { id: uuidv4(), name: "Plate Recognition" },
        { id: uuidv4(), name: "Polarization Controller" },
        { id: uuidv4(), name: "Polarization Maintaining Fiber" },
        { id: uuidv4(), name: "Power" },
        { id: uuidv4(), name: "Power Cables" },
        { id: uuidv4(), name: "Power Control" },
        { id: uuidv4(), name: "Power Converter" },
        { id: uuidv4(), name: "Power Dissipation" },
        { id: uuidv4(), name: "Power Distribution Network" },
        { id: uuidv4(), name: "Power Distribution Systems" },
        { id: uuidv4(), name: "Power Electricity" },
        { id: uuidv4(), name: "Power Electronic" },
        { id: uuidv4(), name: "Power Electronic Drives" },
        { id: uuidv4(), name: "Power Electronics and Drives" },
        { id: uuidv4(), name: "Power Energy" },
        { id: uuidv4(), name: "Power Engineering" },
        { id: uuidv4(), name: "Power Generation" },
        { id: uuidv4(), name: "Power Network" },
        { id: uuidv4(), name: "Power Protection" },
        { id: uuidv4(), name: "Power Quality" },
        { id: uuidv4(), name: "Power Quality Improvement" },
        { id: uuidv4(), name: "Power Supply Systems" },
        { id: uuidv4(), name: "Power System Optimization" },
        { id: uuidv4(), name: "Power Systems" },
        { id: uuidv4(), name: "Power Technology" },
        { id: uuidv4(), name: "Power Tramsmission" },
        { id: uuidv4(), name: "Power Transformers" },
        { id: uuidv4(), name: "Precision Agriculture" },
        { id: uuidv4(), name: "Predicitve Mantenaince" },
        { id: uuidv4(), name: "Privacy" },
        { id: uuidv4(), name: "Privilege" },
        { id: uuidv4(), name: "Process Control" },
        { id: uuidv4(), name: "Process Improvement" },
        { id: uuidv4(), name: "Process Management" },
        { id: uuidv4(), name: "Process Modeling" },
        { id: uuidv4(), name: "Process Optimization" },
        { id: uuidv4(), name: "Processor" },
        { id: uuidv4(), name: "Product Quality" },
        { id: uuidv4(), name: "Production Engineering" },
        { id: uuidv4(), name: "Program Analysis" },
        { id: uuidv4(), name: "Program Slicing" },
        { id: uuidv4(), name: "Programming" },
        { id: uuidv4(), name: "Project Mangement" },
        { id: uuidv4(), name: "PSO Tuning" },
        { id: uuidv4(), name: "Psychoinformatics" },
        { id: uuidv4(), name: "Public Health" },
        { id: uuidv4(), name: "Pulsed Power Technology" },
        { id: uuidv4(), name: "PV Integration" },
        { id: uuidv4(), name: "Pyramidal Techniques" },
        { id: uuidv4(), name: "Python Progamming" },
        { id: uuidv4(), name: "QR Code" },
        { id: uuidv4(), name: "Quality of Service" },
        { id: uuidv4(), name: "Quantum Communication" },
        { id: uuidv4(), name: "Quantum Computing" },
        { id: uuidv4(), name: "Quantum Electronics" },
        { id: uuidv4(), name: "Radar" },
        { id: uuidv4(), name: "Radar Detectionand Recognition" },
        { id: uuidv4(), name: "Radar Imaging" },
        { id: uuidv4(), name: "RADAR Signal Processing" },
        { id: uuidv4(), name: "Radial Distribution Networks" },
        { id: uuidv4(), name: "Radio Communication" },
        { id: uuidv4(), name: "Radio Engineering Systems" },
        { id: uuidv4(), name: "Radio Frequency" },
        { id: uuidv4(), name: "Radio Propagation" },
        { id: uuidv4(), name: "Radio Systems" },
        { id: uuidv4(), name: "Radio Wave Propagation" },
        { id: uuidv4(), name: "Radiolocation" },
        { id: uuidv4(), name: "Rain Attenuation" },
        { id: uuidv4(), name: "Random Forest" },
        { id: uuidv4(), name: "Raspberry Pi" },
        { id: uuidv4(), name: "Reactive Power Optimization" },
        { id: uuidv4(), name: "Read Write Operation" },
        { id: uuidv4(), name: "Real-Time Monitoring System" },
        { id: uuidv4(), name: "RealTime Scheduling" },
        { id: uuidv4(), name: "Real-time System" },
        { id: uuidv4(), name: "Recommendation System" },
        { id: uuidv4(), name: "Recurrent Neural Networks" },
        { id: uuidv4(), name: "Regression" },
        { id: uuidv4(), name: "Regression Analysis" },
        { id: uuidv4(), name: "Regular Expression" },
        { id: uuidv4(), name: "Reliability of Power Systems" },
        { id: uuidv4(), name: "Remote Sensing" },
        { id: uuidv4(), name: "Renewable Energy" },
        { id: uuidv4(), name: "Renewable Energy Integration" },
        { id: uuidv4(), name: "Renewable Energy Source" },
        { id: uuidv4(), name: "Renewable Engineering" },
        { id: uuidv4(), name: "Renewable Enrgy Application" },
        { id: uuidv4(), name: "Renewable Power Generation" },
        { id: uuidv4(), name: "Renewable Technology" },
        { id: uuidv4(), name: "RF and Antenna Design" },
        { id: uuidv4(), name: "RF and Microwave Engineering" },
        { id: uuidv4(), name: "RF Engineering" },
        { id: uuidv4(), name: "RF Microwave" },
        { id: uuidv4(), name: "RF Switches" },
        { id: uuidv4(), name: "RFID" },
        { id: uuidv4(), name: "RFID Antenna" },
        { id: uuidv4(), name: "Risk Assessment" },
        { id: uuidv4(), name: "Risk Management" },
        { id: uuidv4(), name: "Road Traffic Accidents" },
        { id: uuidv4(), name: "Robot Vision" },
        { id: uuidv4(), name: "Robotic" },
        { id: uuidv4(), name: "Robotic Control" },
        { id: uuidv4(), name: "Robotic Surgery" },
        { id: uuidv4(), name: "Robotic System" },
        { id: uuidv4(), name: "Robust and Adaptive Controls" },
        { id: uuidv4(), name: "Robust Control" },
        { id: uuidv4(), name: "Rough Set Theory" },
        { id: uuidv4(), name: "Routing" },
        { id: uuidv4(), name: "Routing Protocol" },
        { id: uuidv4(), name: "Sagnac Loop Filter" },
        { id: uuidv4(), name: "SARS-CoV-2" },
        { id: uuidv4(), name: "Satellite Communication" },
        { id: uuidv4(), name: "Satellite Design" },
        { id: uuidv4(), name: "Scattering" },
        { id: uuidv4(), name: "Scattering Theory" },
        { id: uuidv4(), name: "Scheduling" },
        { id: uuidv4(), name: "Science and Engineering" },
        { id: uuidv4(), name: "Secured Computing" },
        { id: uuidv4(), name: "Security" },
        { id: uuidv4(), name: "Security Vulnerability" },
        { id: uuidv4(), name: "Segmentation" },
        { id: uuidv4(), name: "Selection Answer" },
        { id: uuidv4(), name: "Self-test Engineering" },
        { id: uuidv4(), name: "Semantic Relatedness" },
        { id: uuidv4(), name: "Semantic Web" },
        { id: uuidv4(), name: "Semiconductor" },
        { id: uuidv4(), name: "Sensor Networks" },
        { id: uuidv4(), name: "Sensor Technology" },
        { id: uuidv4(), name: "Sensorless Sensing" },
        { id: uuidv4(), name: "Sensors" },
        { id: uuidv4(), name: "Sensors and Instrumentation" },
        { id: uuidv4(), name: "Sentiment Analysis" },
        { id: uuidv4(), name: "Sentiment Mining" },
        { id: uuidv4(), name: "Sign Language" },
        { id: uuidv4(), name: "Sign Language Recognition" },
        { id: uuidv4(), name: "Signal" },
        { id: uuidv4(), name: "Signal and Image Processing" },
        { id: uuidv4(), name: "Signal and Sensor" },
        { id: uuidv4(), name: "Signal Processing" },
        { id: uuidv4(), name: "Signal Strength" },
        { id: uuidv4(), name: "Simmulation" },
        { id: uuidv4(), name: "Simplified-AES" },
        { id: uuidv4(), name: "Singal Procesing" },
        { id: uuidv4(), name: "Single Cantilever" },
        { id: uuidv4(), name: "Skin Cancer" },
        { id: uuidv4(), name: "Smart Agriculture" },
        { id: uuidv4(), name: "Smart Car Parking" },
        { id: uuidv4(), name: "Smart Cities" },
        { id: uuidv4(), name: "Smart Grid" },
        { id: uuidv4(), name: "Smart Home" },
        { id: uuidv4(), name: "Smart Power Systems" },
        { id: uuidv4(), name: "Social Communications" },
        { id: uuidv4(), name: "Social Media" },
        { id: uuidv4(), name: "Social Media Analysis" },
        { id: uuidv4(), name: "Social Network Analysis" },
        { id: uuidv4(), name: "Social Networks" },
        { id: uuidv4(), name: "Social Sciences" },
        { id: uuidv4(), name: "Soft Computing" },
        { id: uuidv4(), name: "Software" },
        { id: uuidv4(), name: "Software Automation" },
        { id: uuidv4(), name: "Software Development" },
        { id: uuidv4(), name: "Software Engineering" },
        { id: uuidv4(), name: "Software Methodologies" },
        { id: uuidv4(), name: "Software Project Management" },
        { id: uuidv4(), name: "Software Testing" },
        { id: uuidv4(), name: "Solar Cell" },
        { id: uuidv4(), name: "Solar Energy" },
        { id: uuidv4(), name: "Solar Photovoltaic" },
        { id: uuidv4(), name: "Solid State Electronics" },
        { id: uuidv4(), name: "Space Radiation" },
        { id: uuidv4(), name: "Spatial Data Analysis" },
        { id: uuidv4(), name: "Spatial Modeling" },
        { id: uuidv4(), name: "Speech Processing" },
        { id: uuidv4(), name: "Speech Recognition" },
        { id: uuidv4(), name: "Speed Control" },
        { id: uuidv4(), name: "Stage Structure" },
        { id: uuidv4(), name: "State Estimation" },
        { id: uuidv4(), name: "Static Converters" },
        { id: uuidv4(), name: "Statistical Machine Learning" },
        { id: uuidv4(), name: "Statistics" },
        { id: uuidv4(), name: "Steam Distillation" },
        { id: uuidv4(), name: "Steganography" },
        { id: uuidv4(), name: "Stereo Vision" },
        { id: uuidv4(), name: "SupervisedLearning" },
        { id: uuidv4(), name: "Supply Chain" },
        { id: uuidv4(), name: "Support Vector Machine" },
        { id: uuidv4(), name: "Sustainable Energy" },
        { id: uuidv4(), name: "Swarm Intelligence" },
        { id: uuidv4(), name: "System Analysis" },
        { id: uuidv4(), name: "System Control" },
        { id: uuidv4(), name: "System Design" },
        { id: uuidv4(), name: "System Engineering" },
        { id: uuidv4(), name: "System Identification" },
        { id: uuidv4(), name: "System Optimization" },
        { id: uuidv4(), name: "System Simulation" },
        { id: uuidv4(), name: "Systems and Electronics" },
        { id: uuidv4(), name: "Systems Engineering" },
        { id: uuidv4(), name: "Systems Reliability" },
        { id: uuidv4(), name: "Technical Losses" },
        { id: uuidv4(), name: "Technology Acceptance" },
        { id: uuidv4(), name: "Technology Management" },
        { id: uuidv4(), name: "Technopreneurship" },
        { id: uuidv4(), name: "Telecommunication" },
        { id: uuidv4(), name: "Telehealth" },
        { id: uuidv4(), name: "Telemedicine" },
        { id: uuidv4(), name: "Tensor Products" },
        { id: uuidv4(), name: "Text Classification" },
        { id: uuidv4(), name: "Text Mining" },
        { id: uuidv4(), name: "Texture Analysis" },
        { id: uuidv4(), name: "Texture Classification" },
        { id: uuidv4(), name: "Texture Feature Extraction" },
        { id: uuidv4(), name: "Time Delay" },
        { id: uuidv4(), name: "Time Series" },
        { id: uuidv4(), name: "Touchless Interaction" },
        { id: uuidv4(), name: "Tourism" },
        { id: uuidv4(), name: "Traction Power Supply System" },
        { id: uuidv4(), name: "Traditional Culture" },
        { id: uuidv4(), name: "Traditional Motif" },
        { id: uuidv4(), name: "Traffic Information and Control" },
        { id: uuidv4(), name: "Transducer" },
        { id: uuidv4(), name: "Transfer Learning" },
        { id: uuidv4(), name: "Transient Stability" },
        { id: uuidv4(), name: "Transmission and Distribution" },
        { id: uuidv4(), name: "Transmission Line" },
        { id: uuidv4(), name: "Transmission Planning" },
        { id: uuidv4(), name: "Transportation" },
        { id: uuidv4(), name: "Treatment System Design" },
        { id: uuidv4(), name: "Ultrasonic Motor" },
        { id: uuidv4(), name: "User Experience" },
        { id: uuidv4(), name: "User Interface" },
        { id: uuidv4(), name: "UWB Antennas" },
        { id: uuidv4(), name: "Validation" },
        { id: uuidv4(), name: "Vedio Processing" },
        { id: uuidv4(), name: "Vehicle Dynamic" },
        { id: uuidv4(), name: "Vehicle Tracking" },
        { id: uuidv4(), name: "Vehicular Ad-hoc Network" },
        { id: uuidv4(), name: "Verification" },
        { id: uuidv4(), name: "Vibration" },
        { id: uuidv4(), name: "Video" },
        { id: uuidv4(), name: "Video Analysis" },
        { id: uuidv4(), name: "Video Forgery Detection" },
        { id: uuidv4(), name: "Video Processing" },
        { id: uuidv4(), name: "Video Transmission" },
        { id: uuidv4(), name: "Virtual Education" },
        { id: uuidv4(), name: "Virtual Private Network" },
        { id: uuidv4(), name: "Visible Light Communication" },
        { id: uuidv4(), name: "Visual Perception" },
        { id: uuidv4(), name: "Visual Surveillance" },
        { id: uuidv4(), name: "Visual Taste Perception" },
        { id: uuidv4(), name: "Visualization" },
        { id: uuidv4(), name: "VLSI" },
        { id: uuidv4(), name: "VLSI Communication" },
        { id: uuidv4(), name: "VLSI Design" },
        { id: uuidv4(), name: "VLSI Testing" },
        { id: uuidv4(), name: "Voice Processing" },
        { id: uuidv4(), name: "Voice Recognition" },
        { id: uuidv4(), name: "VoIP" },
        { id: uuidv4(), name: "Voltage Divider" },
        { id: uuidv4(), name: "Voltage Quality" },
        { id: uuidv4(), name: "Voltage Source Inverter" },
        { id: uuidv4(), name: "Vulnerability" },
        { id: uuidv4(), name: "Water Pumping" },
        { id: uuidv4(), name: "Water Quality" },
        { id: uuidv4(), name: "Water Resources" },
        { id: uuidv4(), name: "Watermarking" },
        { id: uuidv4(), name: "Wavelet Transforms" },
        { id: uuidv4(), name: "Web Design" },
        { id: uuidv4(), name: "Web Development" },
        { id: uuidv4(), name: "Web Mining" },
        { id: uuidv4(), name: "Web of Things" },
        { id: uuidv4(), name: "Weld Bead Geometry Prediction" },
        { id: uuidv4(), name: "Wi-Fi" },
        { id: uuidv4(), name: "Wildlife Conservation" },
        { id: uuidv4(), name: "WiMAX Technology" },
        { id: uuidv4(), name: "Wind" },
        { id: uuidv4(), name: "Wind Energy" },
        { id: uuidv4(), name: "Wind Farm" },
        { id: uuidv4(), name: "Wind Potential" },
        { id: uuidv4(), name: "Wind Power" },
        { id: uuidv4(), name: "Wired Communication" },
        { id: uuidv4(), name: "Wireless" },
        { id: uuidv4(), name: "Wireless and Mobile Application" },
        { id: uuidv4(), name: "Wireless and Mobile Communications" },
        { id: uuidv4(), name: "Wireless Body Area Networks" },
        { id: uuidv4(), name: "Wireless Communication" },
        { id: uuidv4(), name: "Wireless Communication Networks" },
        { id: uuidv4(), name: "Wireless Communication Systems" },
        { id: uuidv4(), name: "Wireless Control" },
        { id: uuidv4(), name: "Wireless Management" },
        { id: uuidv4(), name: "Wireless Network" },
        { id: uuidv4(), name: "Wireless Network and Communiction" },
        { id: uuidv4(), name: "Wireless Network Engineering" },
        { id: uuidv4(), name: "Wireless Networks" },
        { id: uuidv4(), name: "Wireless Optical Communication" },
        { id: uuidv4(), name: "Wireless Positioning" },
        { id: uuidv4(), name: "Wireless Power Transmission" },
        { id: uuidv4(), name: "Wireless Sensor Network" },
        { id: uuidv4(), name: "XML" },
      ];

      await Interest.bulkCreate<InterestType>(InterestObject, {
        validate: true,
        individualHooks: true,
        transaction,
      });
    });
  },

  down: async (queryInterface: QueryInterface): Promise<void> => {
    await queryInterface.sequelize.transaction(async (transaction) => {
      await queryInterface.bulkDelete(Interest.tableName, {}, {});
    });
  },
};
